version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ecomm-paymentservice-postgresql
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      TZ: Asia/Kolkata
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: