server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/payment_db
    username: payment
    password: payment
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.events, com.ecommerce.payment_service.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer


eureka:
  client:
    service-url:
      defaultZone: http://localhot:8761/eureka
    register-with-eureka: false
    fetch-registry: false